---
- name: Configuration du serveur nginx
  hosts: all
  become: yes
  
  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes
        upgrade: yes
      
    - name: Installation de NGINX
      apt:
        name: nginx
        state: present

    - name: Démarrage et activation du service NGINX
      service:
        name: nginx
        state: started
        enabled: yes
        
    - name: Installer Node.js et npm
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes    

    - name: Copie du frontend
      copy:
        src: ../front/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: "0755"
      notify: Reload NGINX

  handlers:
    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded