- name: Installation et configuration de NGINX
  hosts: nginx
  become: yes
  tasks:
    - name: Mise à jour des packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Installation de NGINX
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Démarrage du service NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configuration de NGINX
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Redémarrer NGINX

  handlers:
    - name: Redémarrer NGINX
      service:
        name: nginx
        state: restarted